version: '2'
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=YOUR_API_KEY
      - ZONE=example.com
      - SUBDOMAIN=subdomain
      - PROXIED=true
