version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "81:80/tcp"
      - "444:443/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'safe_password' #change password
      DNS1: '84.200.70.40' # DNS.WATCH
      DNS2: '84.200.69.80'
      ServerIP: '192.168.0.10' # Change ip
    hostname: pi-hole
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
