version: "3"

services:
  traefik:
    image: traefik:v2.0
    restart: always
    container_name: traefik
    ports:
      - "80:80" 
      #- "8080:8080" 
      - "443:443" 
    command:
      - --api.insecure=false # Enabling insecure api, NOT RECOMMENDED FOR PRODUCTION
      - --api.dashboard=true
      - --api.debug=true 
      - --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.filename=./dynamic.yaml
      - --providers.docker.network=web 
      - --entrypoints.web.address=:80 
      - --entrypoints.web-secured.address=:443
      - --certificatesresolvers.mytlschallenge.acme.tlschallenge=true
      - --certificatesresolvers.mytlschallenge.acme.email=your@mail.com # Change email
      - --certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json 
    volumes:
      - ./letsencrypt:/letsencrypt 
      - /var/run/docker.sock:/var/run/docker.sock 
      - ./dynamic.yaml:/dynamic.yaml 
    networks:
      - web
      - default
    #labels:
      #- traefik.enable=true 
      #- traefik.http.routers.api.rule=Host(`traefik.example.com`)
      #- traefik.http.routers.api.service=api@internal" # Enabling the api to be a service to access
networks:
  web:
    external:
      name: web
  default:
    driver: bridge
