version: '3'
services:
  netdata:
    image: netdata/netdata
    restart: always
    hostname: raspberrypi
    ports:
      - 19999:19999

    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    environment:
      - PGID=995
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
